[build]
  publish = "ruta/a/tu/carpeta/public" # Reemplaza con la ubicación de tus archivos públicos

[context.production]
  command = "npm install && pm2 start app.js --name mi-api --watch"
  publish = "ruta/a/tu/carpeta/public"

[context.deploy-preview]
  command = "npm install && pm2 start app.js --name mi-api --watch"
  publish = "ruta/a/tu/carpeta/public"

[context.branch-deploy]
  command = "npm install && pm2 start app.js --name mi-api --watch"
  publish = "ruta/a/tu/carpeta/public"

[context.split1]
  command = "npm install && pm2 start app.js --name mi-api --watch"
  publish = "ruta/a/tu/carpeta/public"
