[build]
  command = "npm install pm2 && npm install && pm2 start app.js --name mi-api --watch"
  publish = "."

[context.production]
  command = "npm install pm2 && pm2 start app.js --name mi-api --watch"
  publish = "."

[context.deploy-preview]
  command = "npm install pm2 && pm2 start app.js --name mi-api --watch"
  publish = "."

[context.branch-deploy]
  command = "npm install pm2 && pm2 start app.js --name mi-api --watch"
  publish = "."

[context.split1]
  command = "npm install pm2 && pm2 start app.js --name mi-api --watch"
  publish = "."
